server:
  port: 9296
  
spring:  application:    name: CONFIG-SERVER
    
  cloud:    config:      server:        git:          uri: https://github.com/vijai-g/config-server
          clone-on-start: true  
  profiles:   
   active: native